hw5 first commit done works
Shcherbakov84/Angular2 pull request #1
Opened 2017-05-08 17:17 UTC by Shcherbakov84

2017-05-08 17:47 UTC, fullstackdb requested changes

2017-05-08 17:47 UTC, fullstackdb commented on homework5/src/app/app.component.html
> +<!--<md-sidenav-container>
необхідно:
видалити закоментовану розмітку

2017-05-08 17:47 UTC, fullstackdb commented on homework5/src/app/app.component.html
> +<br>
необхідно:
реалізувати дану поведінку через css

2017-05-08 17:47 UTC, fullstackdb commented on homework5/src/app/app.component.ts
> +  number: number = 1
необхідно:
видалити змінні які не використовуються

2017-05-08 17:47 UTC, fullstackdb commented on homework5/src/app/product-card.service.ts
> +
необхідно:
видалити не використовувані файли

замітка:
створювати файли (сервіса/моделі/компоненти) тільки при необхідності їх використання. Пусті файли, які відповідно і не використовуються створювати не потрібно.
розміщувати файли структурно. Перемістити файл сервісу або в папку з компонентом або в папку з сервісами.

2017-05-08 17:47 UTC, fullstackdb commented on homework5/src/app/product-card/product-card.component.ts
> +
необхідно:
видалити даний компонент, та його відповідні файли.

причина:
контекст поточної задачі не передбачає поведінки, реалізованої в даному компоненті.
компонент не використовується

2017-05-08 17:47 UTC, fullstackdb commented on homework5/src/app/film-card/film-card.component.html
> +			<input mdInput placeholder="Название фильма" name="filmName" [(ngModel)]="filmName" (keyup.enter)="getFilms()">
необхідно:
підкоригувати розмітку/стилі даного імпуту, для більш коректного відображення (розмістити або по центру, або з будь якої сторони проте в межах контейнеру основного контенту)

причина:
відступи в контейнері основного контенту(картки фільмів) більші ніж даного імпуту, це спричиняє неприємний візуальний ефект 'поломаності' верстки

2017-05-08 17:47 UTC, fullstackdb commented on homework5/src/app/film-card/film-card.component.ts
> +    this.filmName = "Matrix"
необхідно:
видалити зайвий пробіл (перший рядок в ngOnInit)

обговорення:
чому значення змінній присвоюється тут, в ngOnInit ?
якщо значення змінної відоме, його треба присвоювати при її ініціалізації, в строці 11

2017-05-08 17:47 UTC, fullstackdb commented on homework5/src/app/film-card/film-card.component.ts
> +    this.filmCardService.getFilms(this.filmName).subscribe(data => {
загальний коментар:
варто відходити від використання циєї конструкції.
Якщо є крайня необхідність в перевірці, більше читабельніше виглядатиме if(this.filmName) { //code }.
В даному ж випадку краще відійти від перевірки та вжити значення за замовчуванням в строці 21
this.filmCardService.getFilms(this.filmName = 'Matrix').

2017-05-08 17:47 UTC, fullstackdb commented on homework5/src/app/film-card/film-card.service.ts
> +  private extractData(res: Response) {
загальний коментар:

поради:
намагайся використовувати синтаксис es6 з строками. Виглядає явніше.
` `${this.url}filmName` ` замість `this.url + filmName`
форматування:
вживай оператори з нового рядка.
```
this.http.get(`${this.url}filmName`)
                .map(this.extractData)
                .filter(// some code, etc)
```

До відома:
В Angular2x параметри до запиту додаються за допомогою класу URLSearchParams. Приклад:

```
private url: string = "http://www.omdbapi.com/";

getFilms (filmName: string): Observable<any> {
         let params: URLSearchParams = new URLSearchParams();
         params.set('page', 1.toString());
         params.set('s', days.toString());
         return this.http.get(this.url, { search: params })
                                  .map(this.extractData);
```

2017-05-09 14:47 UTC, Shcherbakov84 commented on homework5/src/app/app.component.html
> +<!--<md-sidenav-container>
зроблено

2017-05-09 14:49 UTC, Shcherbakov84 commented on homework5/src/app/app.component.html
> +<br>
<br> видалено, в css додано необхідна розмітка

2017-05-09 14:50 UTC, Shcherbakov84 commented on homework5/src/app/app.component.ts
> +  number: number = 1
видалив

2017-05-09 14:51 UTC, Shcherbakov84 commented on homework5/src/app/product-card.service.ts
> +
файли видалено

2017-05-09 14:51 UTC, Shcherbakov84 commented on homework5/src/app/product-card/product-card.component.ts
> +
зроблено

2017-05-09 14:52 UTC, Shcherbakov84 commented on homework5/src/app/film-card/film-card.component.html
> +			<input mdInput placeholder="Название фильма" name="filmName" [(ngModel)]="filmName" (keyup.enter)="getFilms()">
розмістив по центру

2017-05-09 14:52 UTC, Shcherbakov84 commented on homework5/src/app/film-card/film-card.component.ts
> +    this.filmName = "Matrix"
пробіл видалив

2017-05-09 14:54 UTC, Shcherbakov84 commented on homework5/src/app/film-card/film-card.service.ts
> +  private extractData(res: Response) {
${this.url}filmName не працює. Замінив this.url + filmName на ${this.url}${filmName}

2017-05-09 15:03 UTC, Shcherbakov84 commented on homework5/src/app/film-card/film-card.component.ts
> +    this.filmCardService.getFilms(this.filmName).subscribe(data => {
В визові методу this.filmCardService.getFilms(this.filmName = 'Matrix') не виходить передавати параметр за замовчуванням, постійно показує один і той самий список. Можливо я щось не правильно роблю чи не правильно зрозумів. Мій варіант перевірки не підійде?

2017-05-09 16:18 UTC, fullstackdb commented on homework5/src/app/film-card/film-card.component.ts
> +    this.filmCardService.getFilms(this.filmName).subscribe(data => {
все вірно. Воно так і не повинно працювати)
Я не зовсім чітко висловив свою думку.
Не будемо вдаватись в деталі, якщо є необхідність в перевірці робіть її явною, так як Ви і виправили
`if(this.filmName) { //code }`

2017-05-09 16:27 UTC, fullstackdb commented on homework5/src/app/film-card/film-card.service.ts
> +  private extractData(res: Response) {
опціонально:
- реалізуй запит за допомогою URLSearchParams
- використовуй TypeScript (вказуй в методах що повертається/очікується, інтерфейси і тд)
- опрацьовуй ерори при запитах/респонсах
- валідуй стрінгу перед запитом

2017-05-09 16:29 UTC, fullstackdb approved these changes

2017-05-10 08:46 UTC, merged