hw9 first_commit done works
Shcherbakov84/Angular2 pull request #4
Opened 2017-05-22 20:59 UTC by Shcherbakov84

2017-05-23 09:43 UTC, fullstackdb requested changes

2017-05-23 09:43 UTC, fullstackdb commented on homework9/src/app/app.component.css
> +  .toolbar-button-row {
отступы должны быть одинаковы

2017-05-23 09:43 UTC, fullstackdb commented on homework9/src/app/app.component.html
> +        <md-icon>{{link.icon}}</md-icon> &nbsp; {{link.label}}
забрать символ `&nbsp;`
поместить байндинг данных в `span` / `div` или другой подходящий елемент и сделать отступ (если нужно) при помощи css

2017-05-23 09:43 UTC, fullstackdb commented on homework9/src/app/app.component.ts
> +  links = [
добавить тип к переменной,
пример:
```
private someVariable: any[] = [];
```

2017-05-23 09:43 UTC, fullstackdb commented on homework9/src/app/film-card/film-card.component.ts
> +      this.filmCardService.getFilmById(this.filmId).subscribe(data => {
недопустимое название параметра data. Необходимо переиминовать.
использовать тип, пример
```
(customersList: Customer[]) // its an example, you shouldnt use exactely this naming/types
```

2017-05-23 09:43 UTC, fullstackdb commented on homework9/src/app/film-card/film-card.component.ts
> +  filmItem: {} = {};
Необходимо использовать `Object` вместо `{}`

2017-05-23 09:43 UTC, fullstackdb commented on homework9/src/app/film-card/film-card.component.ts
> +  @Input()
по базовому код полиси и для лучшей читабельности  необходимо использовать @Input() непосредственно с значением, пример:
```
@Input() customerId: string; // its an example, you shouldnt use exactely this naming/types
```

2017-05-23 09:43 UTC, fullstackdb commented on homework9/src/app/services/film.service.ts
> +  private extractItemData(res: Response) {
методы `extractListData ` и `extractItemData ` почти одинаковы.
Необходимо реализовать данное поведение через один метод

2017-05-28 18:46 UTC, Shcherbakov84 commented on homework9/src/app/app.component.css
> +  .toolbar-button-row {
странно, в vscode в этом месте отображается нормально.

2017-05-29 21:02 UTC, fullstackdb commented on homework9/src/app/film-list/film-list.component.ts
> +  filmList : Object[] = [{}];
необходимо убрать значение `[{}]` и оставить пустым

2017-05-29 21:07 UTC, fullstackdb requested changes

2017-05-29 21:07 UTC, fullstackdb commented on homework9/src/app/film-list/film-list.component.html
>  		<film-card [filmId]="film.imdbID"></film-card>
в строке 2 поменять значение кондишена на `isFilmListEmty()`
добавить соответствуйщий метод в компонент
```
private isFilmListEmty(): boolean {
 return this.filmList && !this.filmList.length
}
```

2017-05-29 21:07 UTC, fullstackdb commented on homework9/src/app/shared/film.service.ts
> +    return ( Array.isArray(body.Search) ) ? ( body.Search || [] ) : ( body || {} );
реализовать логику в более понятный способ, пример:
```
let body = res.json();
body = body.search || body;
return body || {}
```

2017-05-31 13:04 UTC, fullstackdb commented on homework9/src/app/film-list/film-list.component.ts
> +  filmList : Object[] = [];
чтобы убрать 'блик' при загрузке убери значение пустого масива, оставь значение пустым,
```
filmList : Object[];
```

2017-05-31 13:07 UTC, fullstackdb commented on homework9/src/app/film-list/film-list.component.html
>  		<film-card [filmId]="film.imdbID"></film-card>
перенеси `*ngFor` в `<film-card>`
в `<md-grid-tile>` поставь `*ngIf="filmList && filmList.length"`

2017-05-31 13:07 UTC, fullstackdb approved these changes

2017-06-07 06:20 UTC, merged